dist: trusty
notifications:
  hipchat:
    rooms:
      secure: qOGrrKXJ0Uq5AwijRBjGtl2AlIJX/Zdy9F60JhUQlNluqyEgnx0hxcWy2oqHObQ0fD3yA5MQmLtf5WPSlQ3YPwOjjtSrtQn1w5c6d+D409BoZ7DrgJryvi7QsnP4v3uPlIM8MYC2GPrt0rKkw9yL7JTfmOMnGG1HE+yxVtdVvGEsEKE5TfGpNH6sgszgtp1dlrxgv4FJoNKENR9kIDOdLVxLU7nCYFWpHhVm/tpk7CmyqkoGMQ0FLGSHI1ae9s6Se6mChu8xg5rGSsWW0ZVkC7X6LEU/+7im2iWLC849UG3UAjznlNOuprNKU6P1JWJheByh45F8DmJHO6NjoHYRUvjgPN/JQ4igtRzF7hwm811gNviwsHlgQ2gRhyRIdMIUwPuxIev2Y8bHoh+3A3KSDuvY5qCbFpY5Zjq7t2ArXnO9a8m3AZEhWedRwYF6U+LeggOL/5wFbDhAvtwG9Pyojpuoxm7bUwsU5sL8bwdktSp4uxjdm+gAkVh99ysTCWL2JJ7CaA8Ossbr6sakWABPa06S3NAYRBNDqXBv7MkD9QrbETPSj11g+YY+QKcfuUYbYnF+doqGe2JBMnVeMHmKyErvgNI4otkxwgcqTJe9cqOmsx7d8F6B/hUm8xzKyY0vKK8MuoXfjiULPjYNIGhWDlknkiCoZ8tXxbj4bnO0Jf4=

matrix:
  include:
  - go: 1.8
    language: go
    install: make bootstrap
    script:
    - make dependencies test
